services:

  backend:
    container_name: backend
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}


  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./res/db:/docker-entrypoint-initdb.d


volumes:
  db_data: