services:

  backend:
    container_name: backend
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}

  vector_db:
    container_name: vector_db
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT_HOST: 0.0.0.0
      QDRANT_PORT: 6334
    volumes:
      - vector_db_data:/qdrant/storage:z 

  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./res/db:/docker-entrypoint-initdb.d


volumes:
  db_data:
  vector_db_data: