
CREATE TABLE IF NOT EXISTS CONVERSATION (
    ID_ serial PRIMARY KEY 
);


-- USER CREATION
CREATE USER sep WITH LOGIN PASSWORD 'sep';

--ACCESS DB
REVOKE CONNECT ON DATABASE ai_assistant FROM PUBLIC;
GRANT  CONNECT ON DATABASE ai_assistant  TO sep;

--ACCESS SCHEMA


--ACCESS TABLES
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC ;

GRANT SELECT, INSERT, UPDATE, DELETE ON  CONVERSATION  TO sep ;



